[2025-07-03 00:04:01,761] ERROR log_exception() L875  Exception on /apispec_1.json [GET] - call_trace=/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flask/app.py L875 
Traceback (most recent call last):
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flasgger/utils.py", line 581, in load_from_file
    enc = detect_by_bom(swag_path)
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flasgger/utils.py", line 616, in detect_by_bom
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/app/controllers/accounts/docs/accounts/list.yml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flasgger/utils.py", line 590, in load_from_file
    enc = detect_by_bom(swag_path)
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flasgger/utils.py", line 616, in detect_by_bom
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/app/controllers/accounts/docs/accounts/list.yml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flasgger/base.py", line 164, in get
    return jsonify(self.loader())
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flasgger/base.py", line 438, in get_apispecs
    specs = get_specs(
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flasgger/utils.py", line 180, in get_specs
    doc_summary, doc_description, doc_swag = parse_docstring(
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flasgger/utils.py", line 641, in parse_docstring
    full_doc = load_from_file(swag_path, swag_type)
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flasgger/utils.py", line 604, in load_from_file
    if package_spec.has_location:
AttributeError: 'NoneType' object has no attribute 'has_location'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flasgger/utils.py", line 581, in load_from_file
    enc = detect_by_bom(swag_path)
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flasgger/utils.py", line 616, in detect_by_bom
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/app/controllers/accounts/docs/accounts/list.yml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flasgger/utils.py", line 590, in load_from_file
    enc = detect_by_bom(swag_path)
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flasgger/utils.py", line 616, in detect_by_bom
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/app/controllers/accounts/docs/accounts/list.yml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flasgger/base.py", line 168, in get
    specs = json.dumps(self.loader())
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flasgger/base.py", line 438, in get_apispecs
    specs = get_specs(
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flasgger/utils.py", line 180, in get_specs
    doc_summary, doc_description, doc_swag = parse_docstring(
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flasgger/utils.py", line 641, in parse_docstring
    full_doc = load_from_file(swag_path, swag_type)
  File "/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/flasgger/utils.py", line 604, in load_from_file
    if package_spec.has_location:
AttributeError: 'NoneType' object has no attribute 'has_location'
[2025-07-03 00:04:01,763] INFO _log() L97   127.0.0.1 - - [03/Jul/2025 00:04:01] "[35m[1mGET /apispec_1.json HTTP/1.1[0m" 500 - - call_trace=/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/werkzeug/_internal.py L97  
[2025-07-03 00:04:01,770] INFO _log() L97   127.0.0.1 - - [03/Jul/2025 00:04:01] "[36mGET /flasgger_static/favicon-32x32.png HTTP/1.1[0m" 304 - - call_trace=/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/werkzeug/_internal.py L97  
[2025-07-03 00:05:03,399] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/werkzeug/_internal.py L97  
[2025-07-03 00:05:03,400] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/werkzeug/_internal.py L97  
[2025-07-03 00:05:04,911] INFO _log() L97   127.0.0.1 - - [03/Jul/2025 00:05:04] "GET /apidocs/ HTTP/1.1" 200 - - call_trace=/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/werkzeug/_internal.py L97  
[2025-07-03 00:05:04,952] INFO _log() L97   127.0.0.1 - - [03/Jul/2025 00:05:04] "[36mGET /flasgger_static/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/werkzeug/_internal.py L97  
[2025-07-03 00:05:04,952] INFO _log() L97   127.0.0.1 - - [03/Jul/2025 00:05:04] "[36mGET /flasgger_static/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/werkzeug/_internal.py L97  
[2025-07-03 00:05:04,953] INFO _log() L97   127.0.0.1 - - [03/Jul/2025 00:05:04] "[36mGET /flasgger_static/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/werkzeug/_internal.py L97  
[2025-07-03 00:05:04,955] INFO _log() L97   127.0.0.1 - - [03/Jul/2025 00:05:04] "[36mGET /flasgger_static/lib/jquery.min.js HTTP/1.1[0m" 304 - - call_trace=/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/werkzeug/_internal.py L97  
[2025-07-03 00:05:05,068] INFO _log() L97   127.0.0.1 - - [03/Jul/2025 00:05:05] "[36mGET /flasgger_static/favicon-32x32.png HTTP/1.1[0m" 304 - - call_trace=/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/werkzeug/_internal.py L97  
[2025-07-03 00:05:05,105] INFO _log() L97   127.0.0.1 - - [03/Jul/2025 00:05:05] "GET /apispec_1.json HTTP/1.1" 200 - - call_trace=/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/werkzeug/_internal.py L97  
[2025-07-03 00:06:44,270] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=/home/david/PhpstormProjects/dev-full-stack/pos-puc-mvp-01-back/venv/lib/python3.10/site-packages/werkzeug/_internal.py L97  
